// src/data/facultyData.js
import courses_images from "@/assets/images/courses";

export const facultyData = [
  {
    title: "Safety, Civil & Professional Training Courses",
    description: "Practical training to build skills and enhance career opportunities.",
    links: [
      { name: "Safety Officer Course", description: `Enhance your career prospects by enrolling in a Safety Officer Course in Lahore, Pakistan—a city known for its vibrant culture and growing industrial sector. As industries expand, the demand for qualified safety professionals is on the rise, making this course an essential stepping stone for anyone aspiring to excel in the field of occupational health and safety.

This comprehensive training program is designed to equip you with the knowledge and skills required to ensure workplace safety, prevent accidents, and manage emergency situations effectively. The Safety Officer Course covers key topics such as risk assessment, fire safety, environmental management, and first aid, among others. Whether you are a fresh graduate, a working professional looking to enhance your skills, or someone seeking a career change, this course provides a solid foundation in safety management practices.

Lahore, with its expanding industries in construction, manufacturing, and energy, offers a perfect backdrop for practical learning and real-world application of safety protocols. The course not only prepares you to meet local regulatory requirements but also aligns with international safety standards, opening doors to global career opportunities.

By completing this course, you’ll gain a competitive edge in the job market, making you an indispensable asset to any organization. Start your journey towards a safer workplace and a rewarding career by enrolling in the Safety Officer Course in Lahore today.` },
      { name: "OSHA 30 Hours Course", description: `To avoid industrial accidents and diseases, the Occupational Health and Safety Act (Occupational Health and Safety Act) was created in 1970. The Occupational Safety and Health Administration (OSHA) states that to guarantee that employees are working in a safe environment, firms are required to set and enforce standards as well as to offer training, awareness, education, and support. It safeguards the safety of its employees by enforcing regulations in various organizations. The best way for OSHA to enforce laws is via inspections. For everyone to take advantage of this course and establish health and safety standards in their workplaces, the United College has chosen to provide the OSHA Safety Course in Pakistan in response to the overwhelming demand for OSHA courses.

We offer top-notch OSHA instruction from licensed instructors and recognized tutors. A major objective of OSHA training is to make employees aware of their rights concerning workplace safety and health issues.

Project managers, safety coordinators, safety specialists, and students who wish to have successful careers in the construction sector are the target audiences for this course. To create a safe working environment, create standards and policies, and put these standards and policies into practice in the workplace, the OSHA Online Course 30 Hours will be beneficial.`},
      { name: "Civil Surveyor Course", description: `People began planning growth over time, and town planning as a profession became a tool for creating better living conditions. Civil surveyor training in Rawalpindi explains the technical data utilized in the profession. Town planners would need to examine a variety of aspects while making plans for a developing city or suburb. The concept would be mostly influenced by current needs, but it would also take expansion and future demands into serious account. A town plan that would serve as the foundation for all development initiatives in the area would ultimately be produced through several inputs, calculations, and forecasts.

The region’s town planning standards would apply to anybody who wished to purchase land and construct a structure there. Without consent, no development proposal would be approved. Below are some further data regarding the civil surveyor course in Islamabad.

Local administrations would be established as a result of the town plan to encourage and enable coordinated development and management. Additionally, these agencies would provide civic infrastructure including roads, sewers, electricity, water, and gas. This infrastructure would typically be created at significant financial investment and would typically only connect privately held parcels of land that had been surveyed by the surveyor general.

The local authority would bill landowners, companies, and inhabitants for the cost of the resultant civil infrastructure through a system of local rates and taxes. It would facilitate efficient movement around the region and the supply of amenities like power, water, or gas, and it would often connect with neighboring districts. The top college in Rawalpindi, Islamabad, for Pakistani students is United College who wish to enroll in a civil surveyor program visit United College of Technology.` },
      { name: "Quality Control Course", description: `Quality control (QC) is a procedure used by businesses to maintain or raise the caliber of their products. Testing units to verify if they adhere to the requirements for the finished product is known as quality control. A quality controller increases a company’s revenue by making the product more appealing to buyers and offering features like extended life, greater utility, and maintainability. Students and professionals in the business with little to no experience in quality control are the target audience for the course. They will have a better understanding of the foundational ideas of quality assurance and control thanks to this training. We are one of the top training facilities in Rawalpindi for quality controllers, and United College provides a one-year course in quality control.

A course refers to a focused educational course of study. Although it is often provided on campus, it can also be done online. People who desire to learn more in-depth information about a subject frequently enroll in courses.

Studying quality management could be of interest to those who wish to ensure that businesses, goods, and services perform to their highest potential. Plans and processes for quality control can be studied by students in programs all over the world.` },
      { name: "CIVIL LAB TECHNICIAN COURSE", description: `The need for workers to create and maintain the roads, transit networks, municipal services, and other infrastructure that we use every day is rising. This includes testing materials, soil, and asphalt. Engineers, technologists, contractors, and consultants can rely on the technical assistance and skills of civil technicians. Engineering businesses, building corporations, public works, transportation, and other industries are examples of potential jobs.

A Civil Engineering Laboratory Technician performs a variety of civil construction material sample and testing tasks, both in the lab and out in the field. To assist in the building, engineering, and design of roads, bridges, and other public infrastructure, the discipline of civil technology includes drawing, mapping, traffic technology, and the study of construction materials. Testing of materials is the measuring of the properties and behavior of things like metals, ceramics, or polymers under different circumstances.

The information so gathered can be used to indicate whether a material is suitable for use in a variety of applications, such as the construction of buildings or airplanes, machinery, or packaging. It is possible to test a full- or scaled-down model of a proposed machine or building. As an alternative, researchers can use mathematical models that make use of well-known material properties and behavior to forecast the structure’s possibilities. All across the world, applications of civil engineering employ materials like bitumen, asphalt, and concrete.` },
      { name: "AUTO MECHANIC COURSE", description: `A fulfilling professional choice is fixing cars and trucks. Join our Car Mechanic Training course for a top-notch educational experience. Learn all you need to know about the auto repair to achieve your certification by diving into a range of activities.

This Automobile Mechanic Training course aims to familiarise you with the basic safety guidelines and equipment required to investigate what’s going on beneath the hood of your car. This auto mechanic training focuses more on proper upkeep so you can take exceptional care of your car. You’ll learn more about tires, IC engines, dashboard indicators, and engine oil with the help of this course. This car mechanic course also covers in detail the drive train, brakes, cooling, fuel, and electrical systems, as well as the vehicle repair sector.

This thorough course on car mechanic training has been divided into several digestible modules that, in our opinion, will make it easier for you to understand each idea, from the most basic to the most complex parts of the course. It truly is a certain technique to achieve success.

This course will improve your knowledge and strengthen your CV by giving you essential skills and a recognized credential attesting to your understanding, whether you are an experienced practitioner or an aspiring professional.

There are no official entrance criteria for the Car Mechanic Training course, thus anybody may enroll. The only need is a desire to study, and there is no upper age restriction. Anyone of any age can enroll in a car mechanic course.`},
      { name: "Chef and Cooking Course", description: `The head cook is often in charge of creating menus, procuring ingredients, monitoring food preparation, and managing the kitchen staff, particularly in restaurants and hotels. Chefs are culinary experts who have received training in all facets of food preparation. Their primary duties are creating menus, managing the kitchen workers, and guaranteeing that the cuisine reaches high standards.

Cooking is an art form that allows a chef to please his patrons as well as his friends, family, and guests. People commonly dine at restaurants to assure food quality and variety, save time, avoid inconveniences, and for some other reasons. As a result, the restaurant business is rapidly growing and chefs’ jobs are becoming more crucial. Take a look at our well-designed Professional Chef Course for Business if you want to establish a career as a professional chef or to please your loved ones. The course teaches you how to prepare excellent meals and gives you access to the best recipes from famous chefs. After completing the course, you may aesthetically showcase culinary products to visitors, clients, and friends.

You will learn how to cook, bake, grill, and fry from our experienced chefs. We provide a range of cooking lessons that let you satisfy your inner gourmet while learning to make delectable meals from across the globe or simply brush up on your skills with our all-time favorite Pakistani cuisine.

In Rawalpindi, Islamabad, Pakistan, the United College of Technology offered culinary courses for professionals. We provide a one-year chef and cooking course diploma that is authorized by the Pakistani government.`},
    ],
    image: courses_images.course1,
  },
  {
    title: "Technical & Professional Diploma Programs",
    description: "Equipping learners with practical skills for global careers.",
    links: [
      { name: "AUTO MECHANIC COURSE", description: `A fulfilling professional choice is fixing cars and trucks. Join our Car Mechanic Training course for a top-notch educational experience. Learn all you need to know about the auto repair to achieve your certification by diving into a range of activities.

This Automobile Mechanic Training course aims to familiarise you with the basic safety guidelines and equipment required to investigate what’s going on beneath the hood of your car. This auto mechanic training focuses more on proper upkeep so you can take exceptional care of your car. You’ll learn more about tires, IC engines, dashboard indicators, and engine oil with the help of this course. This car mechanic course also covers in detail the drive train, brakes, cooling, fuel, and electrical systems, as well as the vehicle repair sector.

This thorough course on car mechanic training has been divided into several digestible modules that, in our opinion, will make it easier for you to understand each idea, from the most basic to the most complex parts of the course. It truly is a certain technique to achieve success.

This course will improve your knowledge and strengthen your CV by giving you essential skills and a recognized credential attesting to your understanding, whether you are an experienced practitioner or an aspiring professional.

There are no official entrance criteria for the Car Mechanic Training course, thus anybody may enroll. The only need is a desire to study, and there is no upper age restriction. Anyone of any age can enroll in a car mechanic course.` },
      { name: "AUTOMOBILE ENGINEERING DIPLOMA COURSE", description:`If you want to study automobile engineering as a diploma, you will be well on your way to a successful career. For Pakistan to assemble and produce its cars and transportation, we need more automotive engineers. This branch of automobile engineering also incorporates electrical, software, and mechanical engineering elements. This is also known as vehicle engineering because you work on the production and invention of buses, motorcycles, and trucks, among other things.

Pakistan has made little progress in this field over the years, but things are changing. If we go back to the 1920s, we were mostly importing vehicles from other countries, but now multinational companies such as Honda, Yamaha, Toyota, and Suzuki are assembling their new models in Pakistan. Furthermore, some local companies, such as Road Prince, Super Asia, and others, are producing products that compete with those hit companies. All of this is due to Pakistan’s huge investment in automobile engineering.

Automobile engineering has received recognition & significance ever because motor automobiles able to wear passengers were in vogue. Now because of the speedy improvement of car element producers and car industries, car engineers are in brilliant demand.` },
      { name: "DRILLING ENGINEER ING DIPLOMA COURSE", description: `The technology utilized in oil and gas wells is called drilling engineering. Drilling engineering includes the planning, development, costing, and operation of oil and gas well operations. The design, testing, and completion of wells are all parts of drilling engineering tasks, which are often completed quickly.

The oil and gas sector employs drilling engineers. To extract oil and gas from the earth’s interior, they are drilling oil wells. They mostly work in offshore or onshore drilling locations. Despite the challenging conditions they face at work, they are typically highly paid. In addition to the actual drilling operation, they are involved in a variety of on-site tasks, such as excellent design, cost estimation, and drilling rig maintenance. To provide our followers and visitors with drilling engineering courses in a variety of drilling categories, we have teamed up with highly qualified teachers.

One of the most renowned and reputable technical colleges in Rawalpindi, Islamabad, Pakistan that offers a two-year diploma in drilling engineering is the United College of Technology.`},
      { name: "OIL AND GAS DIPLOMA COURSE", description: `Minerals, gas, and other natural resources abound in Baluchistan. The Sui region of this province has the greatest gas reserves, which are enough to provide one-third of the nation’s energy requirements. The nation’s engineering education has substantially aided in the extraction of natural resources. All that is required is quality in engineering education, as demonstrated by the consistent supply of qualified engineers who possess the abilities required for expanding industries.

Consider Oil and Gas Engineering if you are interested in working in the oil and gas sector and have a scientific or engineering background. This certification covers the whole product life cycle and has several courses and employable parts that you can take with you into the workforce to gain a range of skills and knowledge.

On offshore drilling platforms and facilities, you will frequently collaborate with other professionals to record drilling information, identify the most fruitful locations, monitor maintenance, health, and safety standards, and maintain a steady flow from a well. You also manage a portion of the site’s superfluous equipment’s decommissioning activities.`},
      { name: "HR MANAGEMENT DIPLOMA COURSE", description: `Human resource management Courses (HRM or HR Courses) train students to make hiring decisions, manage workforce choices, and establish and uphold organizational cultures inside businesses. The primary duties of HR include finding new talent, managing benefits and compensation for employees, providing training, and assessing and enhancing employees’ general performance.

If you enjoy dealing with people as much as you enjoy working with numbers, you should pursue Skills in human resource management. It’s the perfect profession for someone who appreciates giving others the tools and assistance they need to succeed.

Skill in human resource management often offers a broad education. Nevertheless, you have the option of specializing in Training and Development, Compensation and Benefits, Recruiting, Organizational Leadership, or Financial Management once you have earned your Course.`},
      { name: "PROJECT MANAGEMENT DIPLOMA COURSE", description: `Setting corporate goals and accomplishing projects that call for a certain skill set constitute project management. Major enterprises, engineering firms, and technical organizations frequently use project management techniques, but any size or type of office that needs project organization and direction can also use them. The finest project management courses are one method to start a career in this area.

Some of the best project management institutions with a variety of study programs are located in Pakistan. A successful finished product is what project managers aim to produce. Therefore, organizing and supervising all of the processes that result in the final output is what project management is all about. Students may enroll in some of the best project management courses at UK colleges to build a successful career. Students have alternatives to choose from, including bachelor’s, master’s, and higher-level courses. On this page, you may find a list of the best institutions, their course offerings, scholarships, and more.`},
      { name: "HVAC TECHNICIAN COURSE", description: `Before seeking more practical training or a work position, students who wish to learn about heating, ventilation, and air conditioning (HVAC) in construction enroll should enroll in the HVAC Technologies Theory Course. This might serve as initial training for a new hire, and as a refresher for those currently employed in the pursuit of pursuing additional training and a career role.

With workshop time accounting for more than 80% of the course, our Total Air Conditioning and Refrigeration training courses are intended to be as practical as they possibly can be.

We think that the best way to learn is by doing, thus during the Total Air Conditioning and Refrigeration training cousins Allu will install repair, fault identification, adapt, and common several different pieces of equipment. After completing ANY of our courses, we provide access to a plethora of knowledge and information as well as impartial technical help. After finishing your training with Technique, you may be confident.`},
      { name: "PLUMBING COURSE", description: `The water supply and water drainage systems are the two most crucial and significant building-related elements. Plumbing entails emptying the water system and is responsible for supplying hot or fresh water to the building’s fixtures. This course has been specifically created by The United College of Technology (PVT) LTD. for students who want to major in plumbing or a related field. With the support of United College of Technology (PVT) LTD., you have the chance to discover who you are and obtain knowledge, practical experience, and respect in the fields of plumbing and sanitation. At the United College of Technology (PVT) LTD., you will receive hands-on experience in the theory that sets us distinct from our rivals as well as a practical understanding of certain fields of construction.

For those interested in becoming plumbers, United College provides two monthly certificate training programs. Candidates earn a certificate after completing their theoretical and practical training to become a plumber. There is a campus facility as well. We are one of the most well-known plumbing training facilities in Rawalpindi.`},
    
    ],
    image: courses_images.course2,
  },
  {
    title: "Professional & Technical Training Programs ",
    description: "Career-focused courses to gain skills across safety, technology, and management.",
    links: [
      { name: "BUILDING ELECTRICIAN COURSE", description: `There are many various levels of electrician courses we offer, so no matter if you want to start a career as an electrician and break into the field or if you are a trained electrician already and want to expand your skills or knowledge, we will have the right course for you. We can give unbiased advice on the best training for your specific situation since we can deliver practical electrical training to both seasoned electricians and fresh beginnings.

We think the greatest way to learn is by doing, thus our courses are made to be as practical as possible! All of our courses are given by qualified, skilled business professionals. We have training facilities all around Pakistan, and they are all outfitted with cutting-edge tools so that applicants may practice and work with them. These are just a few of the reasons why our electrical training courses have excellent pass rates. We provide electrical training courses to equip you with the necessary abilities, whether you’re a beginner trying to get electrical experience or a seasoned electrician searching for more commercial or industrial employment.

Our course advisers are extremely knowledgeable and can provide excellent guidance if you need assistance in scheduling your next electrical training session.` },
      { name: "INDUSTRIAL ELECTRICIAN COURSE", description: `An industrial electrician is an electrician who supervises electrical controls, wiring, and workplace machinery in an industrial facility. They work for a variety of enterprises, such as steel manufacturing facilities, electrical companies, and part makers. Industrial electricians may work for one firm exclusively or as independent contractors. The Industrial Electrician course is intended to give students the required training in the electrical trade, including the safety, electrical code, equipment, solar panel installation, and trade knowledge curricula.

An advanced degree qualifies one to be an electrician. Two semesters of six months each make up the one-year duration of this course. Students will be able to construct or maintain a variety of authorized wiring techniques for the distribution of electrical light, radio, heat, power, and signaling usage systems after finishing this course. Their job often entails installing streets and traffic signals as well as different above- and below-grade exterior installations in new or existing residential, commercial, and industrial facilities. It is career-oriented and will provide graduates with a wide range of employment opportunities.` },
      { name: "BEAUTICIAN COURSE", description: `A major issue with public health is food safety. Food and halal safety has emerged as crucial concern for buyers, merchants, producers, and authorities. This program was created by United College to help professionals understand the roles and difficulties of business experiences throughout the halal certification process as well as to enhance halal food safety and insurance skills. With technical learning modules on topics like good documentation requirements, food safety, and industry-friendly halal control systems, this program will provide a comprehensive understanding and emphasis on both food safety and halal aspects, with a focus on application practices in actual food processing environments around the globe.` },
      { name: "FOOD SAFETY COURSE", description: `In Rawalpindi, Islamabad, Pakistan, United College is currently offering a beautician education designed exclusively for women in society. The goal of this course is to give women who want to develop their talents and participate in the real-world environment of entrepreneurs a platform. It is one of the best salon courses in Rawalpindi Islamabad Pakistan with the best and most experienced trainer. Who not only guides you but practically gives you a diploma so that you can open your salon or get training or a job in any renowned beauty center.

Another project is a beautician training in Rawalpindi, Islamabad, Pakistan. This course’s primary goal is to give women and beauticians the skills and information they need. In today’s competitive environment, a beautician must be educated and well-trained to succeed in her line of work. Students who participate in this course will study not only local information and skills but also global trends in the beauty business. This course offers opportunities for skill improvement in addition to being a source for learning new information from scratch.` },
      { name: "Fire Safety Officer Course", description: `Significant fires happen every year, and the ensuing fire or smoke causes people to die or sustain serious injuries in every nation on earth. The inability to exit the facility securely will be a factor. Preventing fires is the greatest strategy for fire safety. This objective may be achieved with proactive fire safety management. Unimpeded safe escape routes, coupled with defined and well-practiced fire safety management strategies, have been demonstrated to lessen the chance of harm and its effects when these occurrences occur. Understanding the fire safety precautions needed to abide by local building and fire standards is crucial for building managers.

When appropriate fire safety inspectors must make sure that facility owners and users clearly understand their role in fire prevention and provide adequate means of orientation for occupants to safely evacuate a building in response to such an incident, proactive management is essential to ensure that building users are aware of their responsibilities in applying these measures. These themes are covered throughout the course, which starts with a discussion of fire prevention strategies.` },
      { name: "WEB DEVELOPMENT COURSE", description: `All the activities involved in launching a website are referred to as web development. In most cases, it refers to the programming and coding side of creating websites rather than the web design part. It includes everything from a straightforward HTML text page to complex, feature-rich applications created to be accessible from a variety of internet-connected devices. Feature-rich web development may be seen in social networks, content management systems, and e-commerce websites, to name a few. HTML, CSS, JavaScript, PHP, and Cascading Style Sheets are common computer languages and tools used in web development.Your online programming journey only really begins with front-end development. You may need to research publications in database programming and well-known programming languages like java and PHP if you want to build reliable websites. In only a few short weeks, you can start developing websites if you enroll in one of these beginner books. In Rawalpindi, Islamabad, Pakistan, the United College of Technology offers a Web Development Course.`},
      { name: "WEB DESIGNING COURSE", description: `In a word, web design is the art and technology of creating a website’s or web page’s appearance, feel, and functionality. Your audience will eventually like using your website more if it has an easy-to-use user interface. Successful website design includes a variety of elements, including html, html5, cascading style sheets, colours, java script, responsive design, layouts, social media, font size, pictures, and much more. For an internet browser to render your material, proficiency in a wide range of computer languages, code optimization, and more may be essential. You’ve come to the right place if you’ve been wondering how to examine web and UX design. Online web design courses are available via United College for all degree levels. The World Wide Online Consortium’s CSS fundamentals instructs you on a variety of design subjects, including best practises in web design, design principles, design tools, and much more. You could find strategies to use CSS style to transform your web pages from boring to powerful. Learn how to use relative positioning in CSS to construct web page layouts, as well as the basic selection of CSS attributes.

Being successful online requires great web and graphic design. Here at United College, we provide a variety of web design and user interface design instructions to meet your needs. To assist you enhance your career, we offer a few online courses in web layout. Whether you’re looking for introductory web design classes or something more advanced, we have you covered. At United College, we only provide the most enjoyable online and practical web design courses to help you succeed.` },
      { name: "SHORT HAND COURSE", description: `This program has been designed to provide newcomers with the practical shorthand abilities needed on the job, especially in the government sector. The student will be equipped to take dictation with this instruction and produce the desired output in his job. Shorthand methods need substantial time to remember tens of thousands of outlines and are based on assigning a single-word outline. Many shorthand sketches require daily, persistent practice to keep all the remembered symbols in mind. Based on the size and thickness of the symbols, it might be able to explain the rules of shorthand to you. People who already grasp the education will be able to use it more quickly and accurately thanks to this education. It’s challenging to train and get up to speed. Shorthand writing is an abridged form of symbolic writing that speeds up and shortens writing compared to writing in ordinary language. Stenography is the term used to describe the abbreviated writing process. Many quick-hand bureaucracies exist, but their standard forms utilize symbols or abbreviations for words and everyday expressions.United College is offering the pit-man education that is sought after and used in respected places in Pakistan.` },
      { name: "QCQA COURSE", description: `In the discipline of metabolomics, quality assurance, and quality control must be used to ensure the collection of high-quality data. In this course, you will learn about the value of quality assurance and control in both untargeted and targeted metabolomics research. We’ll discuss the differences between quality assurance and quality control as well as how to use them both in lab and research settings. In this section, you’ll evaluate the many quality control sample types that may be utilized in metabolomics, the best quality control sample to employ in your research, and how to use the data in your quality assurance strategy to produce reliable and reproducible results.

The course’s contents are sent over three weeks using the Future Learn platform, with a suggested learning time of four hours each week. You will go through several steps each week to finish the study material. A step may consist of a little video, an essay, a task with clear instructions, a peer-to-peer dialogue, or any number of exams, quizzes, or polls that allow you to assess your learning. You may complete the assignments whenever it is most convenient for you because all of the course materials are uploaded on the Future Learn platform.`},
          { name: "SOFTWARE ENGINEERING COURSE", description: `To build, install, and test new software, software engineering focuses on analyzing the needs and requirements of users. Software engineers must be proficient in popular programming languages like SQL, JavaScript, Java, C#, Python, PHP, and others to create applications. Because technology and software programs are utilized in practically every business, the work of software engineers has grown more and more significant. Some of the major problems for software developers are the need for more complicated software and the necessity to provide safe and reliable systems.

Computer programming, algorithms, data structures, HCI, web development, software project management, architecture, and operating systems, security and usability, social responsibility and ethics, etc. are some of the subjects covered in software engineering.

Usually, teams of software developers work together. They can work on a variety of projects, including creating software operating systems, video games, and apps for use in corporate settings. You’ll spend a lot of time writing design specification papers and other files as a software engineer. This stage is essential to ensuring that the software engineering process is well-organized.

Software developers have two options for writing code: either they do it themselves or they give computer programmers instructions or specifications to follow. They spend time identifying possible issues and solving them before they arise. They also take into consideration hardware limitations.

Graduates of software engineering can find employment as software testers, web designers, database administrators, game developers, application developers, and more.`},
      { name: "IOSH MS Course in Lahore Pakistan", description: `The Chartered organization for safety and health professionals is the Institution of Occupational Safety and Health (IOSH). A UK-based organization called IOSH offers professional certifications to improve workplace health and safety standards. The mission of IOSH is to promote sustainable, safe, and healthy work practices around the world.

Around 179,000 people receive certification from the Institution of Occupational Safety and Health (IOSH) each year, giving them the skills necessary to effectively manage workplace health and safety. Our courses provide a great balance of current theory and practice because of our more than 60 years of experience and our long-standing relationship with IOSH. Our IOSH training courses are intended for individuals from a range of sectors and work types and are delivered by qualified instructors.

In Pakistan, United College of Technology (Pvt) Ltd. currently provides top-notch instruction in IOSH courses with current certifications. The reason United College is regarded as the top IOSH training College in Rawalpindi, Islamabad, Pakistan, is that we understand your worries about your educational needs. No matter where you are in the globe, we are IOSH approved and provide all the tools, training, advice, and support you require to create a safer and healthier workplace.` },
      { name: "NEBOSH IGC Course in Lahore", description: `One of the most respected occupational health and safety credentials in the world is the NEBOSH International General Certificate in Occupational Health and Safety (IGC). It teaches you everything you need to know and do to prevent accidents among people and improve the efficiency of your business.

Anyone working in the construction business who wants to learn more about construction-related health and safety should take the NEBOSH Health and Safety Management for Construction certification. The certificate is a top construction course abroad and is held by more than 50,000 people.

This course is closely connected with the Construction (Design and Management) Regulations 2015 and covers prevalent construction hazards, regulatory requirements for health and safety in the construction sector, and reasons for health and safety management.

As a Gold Standard NEBOSH Learning Partner, United College of Technology offers top-notch course materials and knowledgeable instructors while giving training. For those who learn best via tutor interaction and for those who are unfamiliar with the course material, our classroom training courses offer a tutor-led, interactive learning experience.` },
      { name: "Civil Technology Course", description: `The scientific minds underlying the functioning of our contemporary towns and cities are civil engineers. Civil engineers, who are in charge of infrastructure on a broad scale, are engaged in the planning and design of everything from the new village hall to the nation’s energy supply.

These highly specialized individuals must grasp the planning, budgeting, management, and analysis of projects of all sizes by fusing their theoretical and practical engineering expertise.

With a degree in civil engineering, you will be prepared for a broad choice of occupations by combining your natural curiosity, your skill with Lego or Meccano, and your academic intellect. Civil engineering is a field that is both gratifying and hard, from the actual, hands-on work to the rigorous theoretical requirements.

As they pass the buildings and bridges they helped construct every day, civil engineers may take satisfaction in their accomplishments.

Planning, budgeting, surveying, and construction management are all part of the civil engineering process, which involves designing and implementing infrastructure projects. This course, which is a component of United College’s civil engineering and infrastructure cluster, explores the sociological, economic, and practical concerns associated with building. Students with these talents are in great demand. This need is rising as the construction industry continues to expand internationally, where it presently employs more than five million people. This course seeks to fill a critical skills gap. It is intended to be cutting-edge and modern, satisfying business requirements.`},
      { name: "HOTEL MANAGEMENT DIPLOMA COURSE", description: `The expansion of the hospitality sector has increased job prospects and career options in a variety of fields, most notably the specialty of hotel management. Excellent interpersonal skills and a keen grasp of public relations and marketing are prerequisites for employment in this field.

Strategic concerns, business competencies, accounting, finance, marketing, operations, public relations, administration, and management are the main topics covered in united College hotel management courses. Your research will broaden your understanding of the whole hospitality and tourist sector, including client-focused situations, hotels, restaurants, cruise ships, theme parks, destination marketing organizations, conference centers, and country clubs.

The requirement for qualified workers in the hotel sector is constant as it expands internationally. By studying hotel management at United College, you may prepare for a wide choice of high-level employment in a cutthroat job market.`},
],
    image: courses_images.course3,
  },
  {
    title: "Faculty of Humanities & Social Sciences",
    description: "Fostering critical thinking and cultural understanding.",
    links: [
      { name: "OTHM Level 6 Diploma Course", description: `The Level 6 qualifications in Occupational Health and Safety are developed to provide learners who have or are looking to develop into a senior role in an organization for managing health and safety policy and practice. Learners will gain the skills and knowledge to understand the legal and regulatory background of occupational health and safety policies, to be able to assess policies, and to recommend and implement policy changes.

Learners will develop knowledge and skills relevant to putting policy into practice, utilizing management systems, resources, risk and incident management, leadership, management, and skill development. Individuals successfully completing the diploma qualification will be eligible to apply for the graduate level of membership Grad IOSH.`},
      { name: "OTHM Level 3 Technical Certificate Course", description: `The OTHM Level 3 Technical Certificate in Occupational Health and Safety has been developed to enable learners to gain an understanding of health and safety practices within a working environment.

The course provides an insight into how to manage workplace issues and covers the areas you would encounter in a health and safety role.

The aims of this program will allow learners to:

Understand the different roles and responsibilities for health and safety in the working environment
Be aware of safety and welfare rules in the working environment
Understand the elements of a health and social policy
Understand the benefits of safety management systems in organisations
Be able to review health and safety procedures across an organisation
Be able to communicate effectively when contributing to the maintenance of a healthy and safe work environment
Understand the importance of working with others to maintain a healthy and safe workplace.
Understand the principles of risk assessment
Understand the risks and control methods for workplace hazards
Know how to manage the effects of accidents and incidents
Be able to monitor risks and incident management

The qualification is suitable for those wishing to work in health and safety positions in a variety of sectors and will provide the real-world knowledge and skills that organizations and employer’s demand.

Individuals successfully completing the qualification will be eligible to apply for Associate (AIOSH) / Technical (Tech IOSH) membership.` },
      { name: "NVQ Level 6 Diploma in Occupational Health And Safety", description: `The NVQ Level 6 Diploma in Occupational Health and Safety represents a pinnacle of achievement in the field, offering professionals an advanced pathway to mastering the intricacies of workplace safety management. This diploma program is meticulously designed to equip participants with a deep understanding of occupational health and safety principles, practices, and regulations. Recognized internationally, it serves as a testament to an individual’s expertise and dedication to fostering safe work environments.

Throughout the program, participants delve into a comprehensive curriculum that covers a wide array of essential topics. From risk assessment and hazard control to legal compliance and accident investigation, every aspect of occupational health and safety management is thoroughly explored. This breadth of knowledge enables graduates to not only identify potential hazards but also to develop and implement effective strategies for mitigating risks and ensuring the well-being of workers.

One of the distinguishing features of the NVQ Level 6 Diploma is its emphasis on practical application. Participants are encouraged to apply their learning in real-world scenarios, whether through case studies, simulations, or workplace projects. This hands-on approach not only reinforces theoretical concepts but also fosters the development of critical thinking and problem-solving skills essential to success in the field.

In addition to technical proficiency, the program also cultivates strong leadership and communication skills. Graduates emerge as confident and articulate advocates for workplace safety, capable of engaging with stakeholders at all levels of an organization. Whether it’s drafting safety policies, conducting training sessions, or leading safety committees, they are well-equipped to drive positive change and instill a culture of safety within their organizations.`},
      { name: "IT Diploma Course", description:`United College of Technology (Pvt) Ltd is a Professional organization established in 2020, affiliated with SDA, RCC, FBR, SECP Government of Pakistan, and Internationally Awarding Bodies……

United College is the only Technical & Professional College in Pakistan.

United College Provide One & Two Years Diploma Program Like, Safety Officer, HSE Engineering, NEBOSH, IOSH, OSHA, Fire Safety ,Food Safety, First Aid, Civil Engineering ,Civil Surveyor ,Quantity Surveyor ,AutoCAD ,Civil Draftsman…

Civil Lab Technician, Material Testing, Quality Control QC, Quality Assurance QA,QMS,TQM, Air Ticketing ,Travel Agent, Chef and Cooking ,Professional Cooking, Auto Electrician .

EFI Auto Electrician, Auto Mechanic, Automobile Engineering, Automotive, Petroleum Engineering, Drilling Engineering Oil and Gas Rig Courses, Hotel Management..

International Hotel Management, Tourism Management, Restaurant Management, Event Management , Human Recourse Management, Business Management , Project Management, Disaster Management .

IR Management, AC Technician, Refrigerator & Air Conditioning Technician , HVAC , Plumber Course, Welding Diploma, Building Electrician Course, Industrial Electrician, DIT Diploma in Information Technology , CIT Certificate in Information Technology , Basic Computer Course , MS Office , Office Management , Graphic Designing , Web Development, Web Designing ,SEO Search Engine Optimization, Digital Marketing , Freelancing , Accounting Courses, Tally Peachtree , Quick Books , SAP ERP , GIS Course , CCTV Operator Course , Short Hand , Computer Operator, Mobile Repairing,

A +Computer Hardware , Lap Top Repairing, REVIT , 3D Max Course , Civil 3D Course, Primavera P6 , Fiber Optics Training , Scuff folding Inspector , Security Officer , Steel fixer , Supervisor Diploma , Foreman Course ,Beauticians Course, Fashion Designing Course , Spoken English Word Press Development ,

Video Editing Course , Korean Language Course , CCNA Course , CCNP Course , Electrical Engineering , Mechanical Engineering , Chemical Engineering , Telecom Engineering , Software Engineering , DM Diploma And Other 100+ Diploma Courses.`},
      { name: "Computer IT Course", description: `United College of Technology (Pvt) Ltd is a Professional organization established in 2020, affiliated with SDA, RCC, FBR, SECP Government of Pakistan, and Internationally Awarding Bodies……

United College is the only Technical & Professional College in Pakistan.

United College Provide One & Two Years Diploma Program Like, Safety Officer, HSE Engineering, NEBOSH, IOSH, OSHA, Fire Safety ,Food Safety, First Aid, Civil Engineering ,Civil Surveyor ,Quantity Surveyor ,AutoCAD ,Civil Draftsman…

Civil Lab Technician, Material Testing, Quality Control QC, Quality Assurance QA,QMS,TQM, Air Ticketing ,Travel Agent, Chef and Cooking ,Professional Cooking, Auto Electrician .

EFI Auto Electrician, Auto Mechanic, Automobile Engineering, Automotive, Petroleum Engineering, Drilling Engineering Oil and Gas Rig Courses, Hotel Management..

International Hotel Management, Tourism Management, Restaurant Management, Event Management , Human Recourse Management, Business Management , Project Management, Disaster Management .

IR Management, AC Technician, Refrigerator & Air Conditioning Technician , HVAC , Plumber Course, Welding Diploma, Building Electrician Course, Industrial Electrician, DIT Diploma in Information Technology , CIT Certificate in Information Technology , Basic Computer Course , MS Office , Office Management , Graphic Designing , Web Development, Web Designing ,SEO Search Engine Optimization, Digital Marketing , Freelancing , Accounting Courses, Tally Peachtree , Quick Books , SAP ERP , GIS Course , CCTV Operator Course , Short Hand , Computer Operator, Mobile Repairing,

A +Computer Hardware , Lap Top Repairing, REVIT , 3D Max Course , Civil 3D Course, Primavera P6 , Fiber Optics Training , Scuff folding Inspector , Security Officer , Steel fixer , Supervisor Diploma , Foreman Course ,Beauticians Course, Fashion Designing Course , Spoken English Word Press Development ,

Video Editing Course , Korean Language Course , CCNA Course , CCNP Course , Electrical Engineering , Mechanical Engineering , Chemical Engineering , Telecom Engineering , Software Engineering , DM Diploma And Other 100+ Diploma Courses.`},
      { name: "ECU Repairing and Programming Course", description: `Finding an ECU (Engine Control Unit) repairing and programming course in Rawalpindi and Islamabad can be a valuable step for those interested in automotive electronics. These courses can equip you with the knowledge and skills needed to diagnose, repair, and program ECUs, which are crucial components in modern vehicles.

One option is to explore technical schools and colleges in the area. Many of these institutions offer automotive technology programs that encompass ECU-related subjects. It’s advisable to contact them directly or visit their websites to see if they have specific courses or modules on ECU repairing and programming.

Online searches can also be a useful way to discover ECU courses in your region. By using search engines and relevant keywords, you can identify training centers or institutions that provide such programs. Make sure to verify the course details, duration, and the qualifications of the instructors.

Another avenue to consider is reaching out to local automotive workshops and garages. These establishments often have experienced technicians who might offer training programs or can recommend where to find ECU-related courses. Their insights can be valuable in understanding the practical aspects of ECU repair and programming.

Industry associations related to the automotive sector can be another valuable resource. These organizations may maintain lists of training providers or be aware of reputable institutions offering courses in ECU repair and programming. Contacting them for guidance can help you make informed choices.

If you are unable to find local courses, you might consider online learning platforms. Many reputable websites and educational providers offer courses and tutorials in automotive electronics, including ECU-related topics. Online courses can provide flexibility and accessibility, allowing you to learn at your own pace.

Lastly, keep an eye on local advertisements, such as those in newspapers, community centers, and online classifieds. Occasionally, training programs or workshops related to ECU repair and programming are promoted in these channels. Ensure to research the credibility and quality of any courses you discover through these means.

In your search for an ECU repairing and programming course in Rawalpindi and Islamabad, it’s essential to evaluate the reputation of the institution or training center, review the course content, and confirm that it covers both ECU repairing and programming, as these skills often go hand in hand in the automotive industry. With diligent research and inquiries, you can find a suitable program to enhance your knowledge and expertise in this field.

The United College of Technology is one of the best colleges for all technical and professional courses in Rawalpindi, Islamabad, Pakistan. We provide practical training in all courses. We have talented trainers and professional labs for all technical courses at our college in Rawalpindi, Islamabad, Pakistan. Our famous courses are the DIT course in Rawalpindi Islamabad, the Graphic Designing course in Rawalpindi Islamabad, the Hotel Management course in Rawalpindi Islamabad, the Safety Officer course in Rawalpindi Islamabad, the Iosh and Osha course in Rawalpindi Islamabad, and the Civil Engineering course in Rawalpindi Islamabad. I have good experience with this; they are the best for any technical, management, IT or professional course in Rawalpindi, Islamabad, Pakistan.

I suggest to all of you that you choose this in college for your education. After you complete your course, we give you a one-year diploma acceptable worldwide.` },
      { name: "Car Immobilizer System Course", description: `A car immobilizer system course in Rawalpindi and Islamabad is a comprehensive training program designed to educate individuals on the operation, installation, and maintenance of car immobilizer systems. Car immobilizer systems are advanced security features that help protect vehicles from theft and unauthorized access. These courses are essential for individuals seeking to enter the automotive security industry or those who wish to enhance their knowledge and skills in this field.

In the introductory phase of the course, students typically learn about the fundamental principles of car immobilizer systems. They delve into the history and evolution of these systems, understanding how they have become a critical component of modern vehicle security. Students gain insights into the increasing importance of car immobilizers in combating car theft, which is a prevalent concern in many urban areas.

The course also provides a thorough overview of the key components and technology behind car immobilizer systems. Students learn about the various types of immobilizers, such as transponder-based, RFID-based, or keyless systems, and how they function to prevent unauthorized vehicle access. This knowledge forms the foundation for the practical aspects of the course, where students get hands-on experience in installing, configuring, and troubleshooting these systems.

As the course progresses, participants delve into the intricacies of car immobilizer programming and customization. They become proficient in reading and interpreting wiring diagrams, understanding the role of immobilizer control units, and utilizing diagnostic tools to diagnose issues effectively. Additionally, students learn how to integrate car immobilizer systems with other vehicle security features, such as alarm systems and remote keyless entry.

The course also covers the legal and ethical aspects of working with car immobilizer systems, emphasizing the importance of complying with local laws and regulations governing automotive security. Students gain a deep understanding of industry standards and best practices, ensuring that their work is not only effective but also responsible and accountable.

In summary, a car immobilizer system course in Rawalpindi and Islamabad offers a comprehensive education on the vital field of vehicle security. With a focus on theory, practical installation, programming, and legal considerations, participants emerge from the course equipped with the knowledge and skills needed to protect vehicles from theft and provide valuable services to car owners and the automotive industry.` },
      { name: "Computerized Car Scanning Course", description: `A Computerized Car Scanning Course in Rawalpindi and Islamabad is a comprehensive and highly specialized training program that equips individuals with the knowledge and skills required to diagnose and troubleshoot modern vehicles using advanced scanning tools. As automobiles have become increasingly sophisticated, car scanning has become an integral part of vehicle maintenance and repair. This course is essential for aspiring automotive technicians, mechanics, and enthusiasts who wish to stay current with the latest automotive technology and deliver high-quality service to their customers.

In the introductory phase of the course, students typically gain an understanding of the fundamental concepts behind car scanning. They learn about the importance of electronic control units (ECUs) in modern vehicles and how these ECUs manage various vehicle functions, from engine performance to safety systems. Students also explore the evolution of automotive diagnostics, highlighting the shift from traditional mechanical diagnosis to electronic and computer-based methods.

The course content goes on to delve into the intricacies of car scanning tools and equipment. Participants learn about the various types of diagnostic tools available, including OBD-II scanners, scan tools, and software applications used for vehicle diagnostics. They become proficient in connecting these tools to a vehicle’s OBD-II port and interpreting the data generated by the scanner.

One of the core aspects of the course is hands-on training in using car scanning tools for real-world diagnosis. Students practice reading diagnostic trouble codes (DTCs), analyzing live data streams, and conducting functional tests to identify and address issues with the vehicle’s engine, transmission, ABS, airbags, and other critical systems.

As the course progresses, students explore advanced diagnostic techniques, such as scope analysis and the use of oscilloscopes, which provide a deeper insight into a vehicle’s electrical and electronic systems. They also learn how to interpret manufacturer-specific diagnostic information and utilize service manuals and technical resources effectively.

Furthermore, the course emphasizes the importance of safety and ethics in automotive diagnostics. Students are trained to ensure that they adhere to industry best practices, maintain data privacy, and use their scanning capabilities responsibly.

In conclusion, a Car Scanning Course in Rawalpindi and Islamabad is an invaluable educational opportunity for individuals seeking a career in automotive diagnostics.` },
      { name: "Key Programming Course", description: `A Key Programming Course in Rawalpindi and Islamabad is a specialized training program designed to equip individuals with the knowledge and skills necessary for the programming and reprogramming of automotive keys and key fobs. In the modern automotive landscape, vehicles are equipped with sophisticated electronic systems that require coded keys for security and access. This course plays a vital role in training automotive technicians, locksmiths, and enthusiasts, allowing them to proficiently handle key programming tasks. With an increasing reliance on electronic key systems, this course is essential for individuals seeking to stay current with automotive technology and provide efficient and effective services in the field.

In the introductory phase of the course, students typically gain an understanding of the key role that electronic keys play in contemporary vehicles. They learn about the transition from traditional mechanical keys to electronic transponder keys and keyless entry systems and the vital security features they offer. Students are introduced to the fundamental concepts of key programming and its importance in the context of vehicle security.

The course content goes on to delve into the various aspects of electronic key systems, including transponders, remote keyless entry, and proximity keys. Participants learn about the underlying technology and how these components communicate with the vehicle’s onboard computer systems. They explore the intricacies of key coding and reprogramming, ensuring a comprehensive understanding of these essential procedures.

One of the core components of the course is hands-on training in key programming techniques. Students practice key programming and reprogramming on various vehicle makes and models, gaining proficiency in reading security codes, initializing new keys, and resolving issues related to lost or malfunctioning keys. They learn to use diagnostic tools and software applications to carry out these tasks effectively.

As the course progresses, students also explore advanced key programming techniques, such as programming keyless entry remotes and smart keys and dealing with keyless ignition systems. They learn how to handle situations involving key fob programming, which is increasingly common in modern vehicles.

The course emphasizes the importance of adhering to legal and ethical considerations, as students are entrusted with the capability to access and program keys for vehicles. They are trained to operate with integrity and professionalism, maintaining data privacy and complying with industry standards.` },
      { name: "Hybrid Car Technology Course", description: `A Hybrid Car Technology Course in Rawalpindi and Islamabad is a cutting-edge training program designed to provide individuals with a deep understanding of hybrid vehicle technology, a field rapidly gaining prominence in the automotive industry. Hybrids represent a significant leap in the quest for more sustainable and fuel-efficient transportation, making this course indispensable for aspiring automotive technicians, engineers, and enthusiasts. This course offers a comprehensive educational journey that explores the innovative hybrid powertrain systems, regenerative braking, and advanced energy management technologies that define these vehicles. Students gain valuable insights into the environmental benefits, energy efficiency, and unique features that set hybrid cars apart from traditional vehicles.

In the introductory phase of the course, students typically acquire a foundational understanding of hybrid vehicle technology. They explore the principles that underpin hybrid systems, including the combination of internal combustion engines and electric motors, as well as the significance of energy recovery and storage. The course provides a historical context, detailing the evolution of hybrid technology and its relevance in today’s automotive landscape.

The course content goes on to delve into the core components of hybrid vehicles, such as the hybrid powertrain, high-voltage batteries, and regenerative braking systems. Participants gain insights into how these elements work together to optimize fuel efficiency and reduce emissions. They also explore the diversity of hybrid configurations, from mild hybrids to plug-in hybrids, and the advantages each offers.

One of the highlights of the course is hands-on experience with hybrid vehicle systems, which may include disassembling and reassembling hybrid powertrains, diagnosing common issues, and practicing safety protocols for working with high-voltage systems. Students are also introduced to advanced diagnostic tools and software used to maintain and service hybrid vehicles.

As the course progresses, students delve into hybrid vehicle maintenance and repair, with a focus on preventive measures and troubleshooting techniques. They learn about the unique challenges associated with hybrid technology, including high-voltage safety procedures and the importance of certified technicians.

The course also emphasizes environmental stewardship and sustainable practices within the automotive industry, encouraging responsible management of hybrid vehicle systems and their impact on the environment.`},
    ],
    image: courses_images.course4,
  },
  {
    title: "IT & Digital Skills Training Programs",
    description: "Enhancing careers with technology, digital marketing, and professional IT skills.",
    links: [
      { name: "Car Programming Course", description: `United College of Technology (Pvt) Ltd is a Professional organization established in 2020, affiliated with SDA, RCC, FBR, SECP Government of Pakistan, and Internationally Awarding Bodies……

United College is the only Technical & Professional College in Pakistan.

United College  Provide One & Two Years Diploma Program Like, Safety Officer, HSE Engineering, NEBOSH, IOSH, OSHA, Fire Safety ,Food Safety, First Aid, Civil Engineering ,Civil Surveyor ,Quantity Surveyor ,AutoCAD ,Civil Draftsman…

Civil Lab Technician, Material Testing, Quality Control QC, Quality Assurance QA,QMS,TQM, Air Ticketing ,Travel Agent, Chef and Cooking ,Professional Cooking, Auto Electrician .

EFI Auto Electrician, Auto Mechanic, Automobile  Engineering, Automotive, Petroleum Engineering, Drilling Engineering Oil and Gas Rig Courses, Hotel Management..

International Hotel Management, Tourism Management, Restaurant Management, Event Management , Human Recourse Management, Business Management , Project Management, Disaster Management .

IR Management, AC Technician, Refrigerator & Air Conditioning Technician , HVAC , Plumber Course, Welding Diploma, Building Electrician Course, Industrial Electrician, DIT Diploma in Information Technology , CIT Certificate in Information Technology , Basic Computer Course , MS Office , Office Management , Graphic Designing , Web Development, Web Designing ,SEO Search Engine Optimization, Digital Marketing , Freelancing , Accounting Courses, Tally Peachtree , Quick Books , SAP ERP , GIS Course , CCTV Operator Course , Short Hand , Computer Operator, Mobile Repairing,` },
      { name: "GIS-Geographic Information System Course", description: `United College of Technology (Pvt) Ltd. is a Professional organization established in 2020, affiliated with SDA, RCC, FBR, SECP Government of Pakistan, and Internationally Awarding Bodies.

United College is the only Technical & Professional College in Pakistan. United College Provide One & Two Years Diploma Programs Like, Safety Officer, HSE Engineering, NEBOSH, IOSH, OSHA, Fire Safety, Food Safety, First Aid, Civil Engineering, Civil Surveyor, Quantity Surveyor, AutoCAD, Civil Draftsman, Civil Lab Technician, Material Testing, Quality Control QC, Quality Assurance QA, QMS, TQM, Air Ticketing, Travel Agent, Chef and Cooking, Professional Cooking, Auto Electrician, EFI Auto Electrician, Auto Mechanic, Automobile Engineering, Automotive,

Petroleum Engineering, Drilling Engineering Oil and Gas Rig Courses, Hotel Management, International Hotel Management, Tourism Management, Restaurant Management, Event Management, Human Resource Management,

Business Management, Project Management, Disaster Management, IR Management, AC Technician, Refrigerator & Air Conditioning Technician, HVAC, Plumber Course, Welding Diploma, Building Electrician Course, Industrial Electrician, DIT Diploma in Information Technology,

CIT Certificate in Information Technology, Basic Computer Course, MS Office, Office Management, Graphic Designing, Web Development, Web Designing, SEO Search Engine Optimization, Digital Marketing, Freelancing,

Accounting Courses, Tally Peachtree, Quick Books, SAP ERP, CCTV Operator Course, Short Hand, Computer Operator, Mobile Repairing, A +Computer Hardware, Lap Top Repairing, REVIT, 3D Max Course,

Civil 3D Course, Primavera P6, Fiber Optics Training, Scuff folding Inspector, Security Officer, Steel fixer, Supervisor Diploma, Foreman Course.`},
      { name: "NETWORKING COURSE", description: `United College of Technology (Pvt) Ltd. is a Professional organization established in 2020, affiliated with SDA,RCC,FBR,SECP Government of Pakistan and Internationally Awarding Bodies .United College is the only Technical & Professional College of Pakistan. United College Provide One & Two Years Diploma Program Like, Safety Officer, HSE Engineering, NEBOSH, IOSH, OSHA, Fire Safety ,Food Safety, First Aid, Civil Engineering ,Civil Surveyor ,Quantity Surveyor ,AutoCAD ,Civil Draftsman, Civil Lab Technician, Material Testing, Quality Control QC, Quality Assurance QA,QMS,TQM, Air Ticketing ,Travel Agent, Chef and Cooking ,Professional Cooking, Auto Electrician ,EFI Auto Electrician, Auto Mechanic, Automobile Engineering, Automotive, Petroleum Engineering, Drilling Engineering Oil and Gas Rig Courses, Hotel Management, International Hotel Management, Tourism Management, Restaurant Management, Event Management , Human Recourse Management, Business Management , Project Management, Disaster Management , IR Management, AC Technician, Refrigerator & Air Conditioning Technician , HVAC , Plumber Course, Welding Diploma, Building Electrician Course, Industrial Electrician, DIT Diploma in Information Technology , CIT Certificate in Information Technology , Basic Computer Course , MS Office , Office Management , Graphic Designing , Web Development, Web Designing ,SEO Search Engine Optimization, Digital Marketing , Freelancing , Accounting Courses, Tally Peachtree , Quick Books , SAP ERP , GIS Course , CCTV Operator Course , Short Hand , Computer Operator, Mobile Repairing, A +Computer Hardware , Lap Top Repairing, REVIT , 3D Max Course , Civil 3D Course, Primavera P6 , Fiber Optics Training , Scuff folding Inspector , Security Officer , Steel fixer , Supervisor Diploma , Foreman Course ,Beauticians Course, Fashion Designing Course , Spoken English Word Press Development , Video Editing Course , Korean Language Course , CCNA Course , CCNP Course , Electrical Engineering , Mechanical Engineering , Chemical Engineering , Telecom Engineering , Software Engineering , DM Diploma And Other 100+ Diploma Courses.`},
      { name: "CIT CERTIFICATE INFORMATION TECHNOLOGY COURSE", description: `Computer information technology is the use and study of computers, networks, computer languages, and databases inside an organization to address real-world problems (CIT). Students are prepared for professions in application programming, networking, system management, and web development through the major disciplines. The courses teach the basics of information technology, including computer hardware and networking. Furthermore, the package covered the entire Office Automation section, which included MS Office comprising MS Word, MS Excel, and MS PowerPoint with the Internet. Furthermore, the program includes graphic design with Adobe Photoshop and web design with Adobe Dreamweaver.`},
      { name: "VIDEO EDITING COURSE", description: `Video editing is the manipulation and arrangement of video shots. Video editing is used to structure and present all video information, including films and television shows, video advertisements and video essays. The most important technique in production is video editing, which involves creating amazing graphics while also engaging viewers. The video editing course will provide you with a basic understanding of the video editing process. Users may now edit videos more easily because to the availability of free software and web information sharing. The united institute offers a large number of video editing courses. In this video editing class which can help you learn how to edit and record videos.` },
      { name: "E COMMERCE COURSE", description: `Online shopping has been popular in recent years. Millions of individuals prefer to purchase things from their favorite websites online. As a result, a slew of websites offering a diverse range of products and services have sprouted up around the world. Typically, an e-commerce website can be established utilizing a variety of sources, but in order to learn how to deal with those sources, an ecommerce course is required. We at United Institute would like to assist you with developing all of the necessary abilities to become an ecommerce website developer.` },
      { name: "DIGITAL MARKETING COURSE", description: `Digital marketing, also called online marketing, is the promotion of brands to connect with potential customers using the internet and other forms of digital communication. This includes not only email, social media, and web-based advertising, but also text and multimedia messages as a marketing channel. Digital marketing is now the requirement for every business and marketing professional. If you ignore digital marketing today, your competitors will take full advantage and will easily overtake you.The united institute offers 100% practical Digital Marketing Courses in Rawalpindi, Islamabad. If you are interested in learning digital marketing. Join us right now! You can enroll in our best digital marketing.` },
      ],
    image: courses_images.course5,
  },
  {
    title: "Business, Finance & Technical Training Programs",
    description: "Practical courses in accounting, management, and modern technical skills.",
    links: [
      { name: "PRIMAVERA P6 COURSE", description: `Primavera P6 Professional Training Course and Project Management is well-known high-performance project management software that is built to handle large-scale, complex, and diverse projects. The Primavera P6 for Planning Course is designed for project managers and business analysts who use or want to utilize the Primavera software for project planning.

Our Primavera P6 Training course aims to provide high-quality instruction that combines fundamental knowledge of core ideas with a hands-on approach. Exposure to current industrial use-cases and situations will assist trainees in scaling up their skills and doing real-time projects using best practices.`},
      { name: "TALLY COURSE", description: `Tally is a well-known accounting and spending tracking software. The Tally course lasts one month. Tally Training and Certification Tally Course is a top tally course that teaches students about GST, TDS, inventory management, and accounting. United Institute continues its aim by offering the best and most advanced Tally certification courses to students and professionals at an accessible pricing structure. Our students are employable and future-ready thanks to our carefully created and thorough Tally curriculum.`},
      { name: "ACCOUNTING & FINANCE DIPLOMA COURSE", description: `Accounting is an important aspect of our daily lives. Although we may not notice it, accounting serves an important function in ensuring that we understand everything there is to know about finances, management, and so on. It’s ingrained in even the most insignificant of things. It’s no surprise that individuals are interested in the accounting industry, and as a result, accounting courses are a popular choice for many people. The accounting diploma is designed to provide working managers with no or little accounting and financial background with the fundamental knowledge and practical skills. By the completion of the course, participants will have a good understanding of contemporary finance and accounting.` },
      { name: "QUALITY ASSURANCE QA COURSE", description:`Quality assurance is the planned and systematic review process of an institution or program to determine whether or not acceptable standards of education,scho;arship and infrastructure are being met,maintained and enhanced.Quality assurance is an element of a successful programming discharge. QA practise results in fewer defects, happier clients, and superior programming. Learning the principles of quality assurance will save you a lot of money on development costs and contribute to more effective advancement life cycles.`},
    ],
    image: courses_images.course6,
  },
  {
    title: "Skill Development & Professional Training Courses",
    description: "Focused programs to build practical, management, and career skills.",
    links: [
      { name: "STEEL FIXER COURSE", description: `A steel fixer cuts and bends reinforced steel before binding it with stirrups formed of previously cut and shaped thinner reinforced steel pieces. Annealed wire is used to manually link the stirrups to the reinforced steel. Following this, reinforcement is ready to be inserted into a building – foundations, slabs, columns, and so forth. If the job is not too demanding, a steel fixer can operate on the spot; modern construction site storage mostly exports reinforcement that the steel fixer had already molded during his daily operations in the storage area.

We offer in Steel Fixer training for professionals who want to work as trade’s people. On construction sites, tradesmen are the specialists who position and fasten steel reinforcing bars, or rebar’s, and steel mesh used in reinforced concrete. These professionals are in charge of attaching spacers and ‘chairs,’ which determine the amount of concrete cover.` },
      { name: "SECURITY OFFICER COURSE", description: `Security officers are front-line personnel who play a crucial role in keeping people secure in a wide range of everyday circumstances and places. They defend property from theft and vandalism, provide personal protection, regulate access to facilities, aid in the maintenance of order, enforce regulations at public events, conduct investigations for clients or employers, and perform other protective services. This course is designed to provide knowledge and training on the protective strategies and preventive measures that security officer must employ in order to carry out their duties competently.`},
      { name: "SOPKEN ENGLISH COURSE", description: `Around the world, spoken English is the most popular course. Because it is easier to write a foreign language such as English than it is to speak it. Speaking English allows you to truly broaden your views, from work opportunities to the ability to communicate with individuals from all over the world. United institute designed course has been specially to help students improve their English speaking, writing, and reading skills so that they are better prepared to compete in the job market as well as in their student life.` },
      { name: "OFFICE MANAGEMENT COURSE", description: `Office management is a profession concerned with increasing overall efficiency and productivity in an office. Office managers are in charge of the day-to-day operations of administrative staff and the administrative functions of a corporation or organization. The office management courses cover all you need to know to succeed in office administration.

Office management is concerned with the coordination, organization, and planning of the office in order to improve the efficiency of office works in any business. In these courses, you’ll learn the essential skills you need to succeed in office management.

Office management set of preference for companies and businesses. Professionals and students can get an office management course in Rawalpindi.

Are you looking for the best institute for Office Management courses in Rawalpindi?  Now united institute of technology Offers Office Management course training in Rawalpindi`},
      { name: "PEACHTREE COURSE", description: `Peachtree is a small and medium-sized business accounting application (SMB). Peachtree allows accountants and managers to automate and manage a variety of accounting tasks, such as reconciling accounts payable and receivable. This sequences shows how simple it is to boost your productivity with basic accounting methods using Peachtree.

You’ll get a solid introduction to general accounting features, as well as step-by-step instructions on how to set up a new company, vendors, and employee payroll, with the help of series host, seasoned accounting professional.

If you want to start an accounting career or become an expert in computerized accounting, Peachtree is the best Accounting Software in the world to learn and make a professional career. Accounting and Peachtree software use will be proved step by step. United Institute of Technology faculty.` },
      { name: "FREELANCING COURSE", description: `Freelancing  are self-employed and often referred to as independent contractors. Freelancers are hired by other companies on a part time or short-term basis, but they do not receive the same compensation as full-time employees or have the same level of commitment to any particular company. United Institute offers a Professional Live Practical Training in Freelancing course. It’s no secret that online freelancing is enabling millions of people to advance their careers, take control of their schedules, and lives better. Grow your online career with Freelancer and provide the best experiences for every customer you work with.` },
],
    image: courses_images.course7,
  },
];
